stages:
  - Build
  - Image
  - Deploy

variables:
    CI_REGISTRY: https://index.docker.io/v1/
    CI_REGISTRY_USER: huseynmi9
    CI_REGISTRY_IMAGE: huseynmi9/hello-app

Build:
  stage: Build
  image: maven:3.8.6-openjdk-18
  script:
    - cd $CI_PROJECT_DIR/my-app
    - mvn package
  artifacts:
    paths:
      - $CI_PROJECT_DIR/my-app/target/*

Image:
  stage: Image
  image:
    name: mgit/base:kaniko-executor-debug-stable
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination "$CI_REGISTRY_IMAGE:afnfrontendapp-$CI_COMMIT_SHORT_SHA" --force
  only:
    refs:
      - main

Deploy:
  stage: Deploy
  image: dtzar/helm-kubectl
  script:
  - mkdir -p $HOME/.kube/
  - touch $HOME/.kube/config
  - cat $KUBE_CONFIG  > $HOME/.kube/config
  - export KUBECONFIG=/$HOME/.kube/config
  - sed -i "s/<CI_COMMIT_SHORT_SHA>/${CI_COMMIT_SHORT_SHA}/g" $CI_PROJECT_DIR/manifests/Deployment.yaml
  - kubectl apply -f $CI_PROJECT_DIR/manifests/.
  only:
    refs:
      - main
